### ISSUE TITLE
Upgrade to Apache 2.4

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#12]
Do in tandem with #11 
Do EZID & N2T together

**Comment by rushirajnenuji** [comment]
Update: Hey @mariagould both the updates have been completed. EZID is running on Linux 2 ( #11 ) with Apache 2.4 on Stage environment: https://uc3-ezidx2-stg.cdlib.org.

re apache upgrade: There were quite a lot of config changes since they retired some existing modules and introduced new ones. We also have installed new SSL certs which are set to expire sometime in October 2021. 

Just seeing a comment over here: 
> Do EZID & N2T together

I don't seem to remember why we came to this conclusion. I don't see any blockers for EZID that would require an update on N2T.

**Comment by mariagould** [comment]
Thanks @rushirajnenuji ! 

I think the N2T comment was in reference to the fact that N2T had not yet pushed its upgrades to production and we might want to coordinate timing. @jkunze can confirm.

**Comment by jkunze** [comment]
It's true that N2T has not yet upgraded, but I can't right now think of a reason the upgrades need to be done at the same time. Either way, EZID and N2T should be aware of when the other is upgraded  so we can figure out how to minimize or eliminate the possibility of downtime.

**Comment by mariagould** [comment]
Closing as this has been replaced by epic #62
