### ISSUE TITLE
Need an alternative to EDINA backup

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#121]
We need to explore an alternative to our previous EDINA backup. 

Background from Rushiraj: 

we have a nightly cron job (set to execute at 2 AM) that performs 2 tasks:
1. make back up of EZID prod store and search database and save it locally on disk.
2. push this backup to a remote server running at EDINA.

After Linux 2 migration we’re having connectivity issues (possibly firewall configuration) with this remote server. 

We reached out to EDINA to let them know we have a different server. While waiting to hear back from EDINA  we disabled the 2nd subtask and let the service keep making the local backups as usual in the interim.

Note: there is also another job that performs this back up of EZID transaction logs hourly and pushes it to EDINA. This is currently disabled because of the same issue.

EDINA has not responded to multiple emails so we need an alternative backup mechanism.

**Comment by marisastrong** [comment]
Capturing some more details on this ticket
Hourly:
(production only) The transaction log is copied to a machine in a physically and administratively separate data center.
Nightly:
(production only) The local "store" database is backed up to timestamped files in a backups dir and then copied to a physically and administratively separate data center.

The store database is the main database, which Django insists must be referenced as the “default” database.  It stores Django’s internal tables; the principal ezidapp_storeidentifier table; user, group, and realm information; caches of shoulders and datacenters; processing queues; identifier statistics; and basically anything and everything needed for mainline processing.  The design goal of the store database is high-throughput transaction speed.


it looks like the backups are running, are the logs purged after a certain time?  it only appears that the last 2 weeks are on local disk.

I wonder since we are only keeping them for 2 weeks, if an alternative option would be to use the mysql snapshots and ask IAS to increase the frequency of backups from weekly to daily.

My assumption is that these backups are to be used in the event of a catastophic situation where we need to restore the system from a recent backup.

We would ask that backup snapshots could be removed after 2 weeks.  It may be a more costly option that simply storing to S3.  If storing to S3, we would need an easy way to retrieve the files.  I know @rushirajnenuji is writing up the steps of how we might recover the service using these backups so where we store the files will impact the restoration process.

**Comment by marisastrong** [comment]
IAS noted that the standard is to snapshot EC2 and RDS instances daily and is occuring for EZID instances. This could satisfy our backup needs.   The RDS daily backups could restore the database to match that of the daily export/dump/backup that is occurring at 2am.  The EC2 backup is less frequent than the hourly export of the transaction logs that are currently occurring.

- [ ] do we still have the need to store files off in a separate physical location?
- [ ] are we comfortable using the RDS daily backups for restoration?
- [ ] can daily backups for the transaction logs suffice?  utilizing the EC2 backups to revert back to previous state?
- [ ] we still need to determine how we can restore files using the backups

**Comment by marisastrong** [comment]
@rushirajnenuji has the scripts that reference the backup files to restore the database.   @mariagould will review SLA to determine if EZID provides assurance that the database could be restored.
Option to write files to the stage EC2 server vs to EDINA.  
Unlikely that requesting hourly snapshot of EC2 is feasible due to costs/management

**Comment by mariagould** [comment]
Decision: we will copy hourly transaction logs to stage and run a script to delete the logs after 2 weeks.

We will need a separate directory for the scripts (check with Ashley if we need more space)

**Comment by mariagould** [comment]
Discussed with Ashley. Copy hourly logs to stage via Rsync as interim solution. Ultimate goal is to set up streaming to S3.

**Comment by rushirajnenuji** [comment]
This task was completed. Transaction log backups are now being made to stage server. We already perform RDS snapshots, so SQL backups are not needed.
