### ISSUE TITLE
Batch ownership change: UCSF Special Collections ARKs

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#41]
We need to do a bulk ownership change and metadata update on three sets of ARKs from UCSF special collections.

Lists of ARKs: 
[ucsf-mount-zion-jan2020.txt](https://github.com/CDLUC3/ezid-service/files/4119633/ucsf-mount-zion-jan2020.txt)
[ucsf-tca.txt](https://github.com/CDLUC3/ezid-service/files/4119634/ucsf-tca.txt)
[ucsf-specol.txt](https://github.com/CDLUC3/ezid-service/files/4119635/ucsf-specol.txt)

The primary owner of these ARKs needs to be the `ucsf-archives` account in EZID. We want user `merritt` to have proxy access.

In addition to changing ownership, we need to do the following with the metadata for these objects:

            >> - Change profile to Dublin Core and populate dc.* fields, including dc.relation
            >> - Leave ERC and mrt.creator metadata as is
            >> - Leave _status as is

Greg ran a similar job previously using the batch registration/update script (https://github.com/CDLUC3/ezid-client-tools/blob/master/batch-register.py). We should be able to follow the same approach here.

**Comment by mariagould** [comment]
Update: Adrian has confirmed that the files are not supposed to be duplicates. Updated files to come and I'll replace them when available).

**Comment by mariagould** [comment]
@rushirajnenuji Adrian has provided the updated files so this task is ready now.

**Comment by rushirajnenuji** [comment]
Hey @mariagould  - this batch processing is now complete. The batches for `ucsf-mount-zion.csv`, `ucsf-tca-xtf.csv` went well, but I was worried about `ucsf-specol-xtf.csv`. There was no issue with the conversion, but the file itself had lots of special characters. 

Here's an example: for id `ark:/13030/hb3q2nb407` the title has value `KyÅ«shÅ« Higo no kuni Kumamoto no san sanâ€™nin kyÅdai Å-onâ€™na` but turns out our application is smart enough to detect these characters. The decoded string displayed on the front end is `Kyūshū Higo no kuni Kumamoto no san san’nin kyōdai ō-on’na`. So we're good on that front.

Also, with the same file `ucsf-specol-xtf.csv` - I got a few errors with `error: bad request - no such identifier`. Here are the identifiers that threw that error - 
1. `ark:/13030/kt8s203907`
2. `ark:/13030/hb0d5nb24f`
3. `ark:/13030/hb996nb8wv`

I have verified and things look okay to me. It would be great if you could verify that as well. Thanks!

**Comment by mariagould** [comment]
Thanks, Rushiraj! This looks good to me overall. I am also seeing the same issue with those three identifiers. I will flag for Adrian/UCSF.

**Comment by mariagould** [comment]
@rushirajnenuji Adrian isn't sure why we're having issues with those 3 ARKs. He sent me the following links for them: 

https://oac.cdlib.org/ark:/13030/kt8s203907/?brand=oac4
https://oac.cdlib.org/ark:/13030/hb0d5nb24f/?brand=oac4
https://oac.cdlib.org/ark:/13030/hb996nb8wv/?brand=oac4

My first hunch was that these hadn't been registered in EZID to begin with and that's why we don't have a record of them. But he says they were registered at the same time as others in the collection. Do you think we can try to (re)register them?

**Comment by mariagould** [comment]
@rushirajnenuji Adrian has followed up to confirm that he thinks these might never have been registered in EZID to begin with. Can you please register them and make sure they have the same ownership/metadata status as the rest of the batch? Thanks!

**Comment by rushirajnenuji** [comment]
Sure, can do! I'll close this ticket when that is done. Thanks @mariagould

**Comment by rushirajnenuji** [comment]
Hey @mariagould  - these 3 identifiers have been created with the same `mappings` as the rest of the batch. Closing this ticket. Let me know if something looks awry.
