### ISSUE TITLE
Create new shoulder: Journal of Evolution and Health

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#84]
EZID prefix/shoulder: doi:10.15310
Account/organization username (login): ucla-eschol
Shoulder display name: Journal of Evolution and Health
Datacenter:

**Comment by mariagould** [comment]
@jkunze this is the UCLA journal whose existing Crossref prefix and DOIs we are transferring _into_ EZID. You mentioned earlier we would approach this by setting up a supershoulder with an attached minter. Let me know your thoughts on next steps.

**Comment by jkunze** [comment]
Since then, I've recalled another way we've set up an account that accommodates both brand new (generated) ids and legacy ids. It might be preferable since there's precedent for it. It involves setting up two shoulders: 

   Shoulder display name: Journal of Evolution and Health
   Shoulder display name: Journal of Evolution and Health (no minter)

The second should is a supershoulder, and permits the registration of the legacy ids. The first shoulder has the usual minter. If you want to go this route, I'd just need the usual shoulder string from you, eg, doi:10.15310/h3 .

**Comment by mariagould** [comment]
Thanks. That sounds good to me. I'll ask the eSchol team what shoulder string they want.

**Comment by mariagould** [comment]
@jkunze let's use the shoulder string J3. Thanks.

**Comment by jkunze** [comment]
OK, shoulders should be in place now.

It took extra time because I was using this instance to test and finish the new scripts, now close to final form.
